apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-cafe
  namespace: default
spec:
  selector:
    matchLabels:
      app: azure-cafe
  replicas: 2
  template:
    metadata:
      name: azure-cafe
      labels:
        app: azure-cafe
    spec:
      containers:
      - name: azure-cafe
        image: azurecaferegistryreza.azurecr.io/azure-cafe:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 8443        
        - containerPort: 9990
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9990
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9990
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: azure-cafe
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
  selector:
    app: azure-cafe
