apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: azure-cafe
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      name: azure-cafe
      labels:
        app: azure-cafe
    spec:
      containers:
      - name: azure-cafe
        image: rezarahman/azure-cafe:v3
        livenessProbe:
          httpGet:
            path: "/health"
            port: 9990
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: "/health"
            port: 9990
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          timeoutSeconds: 10
        env:
        - name: APPLICATION_INSIGHTS_KEY
          valueFrom:
            configMapKeyRef:
              name: application-insights-key
              key: APPLICATION_INSIGHTS_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: azure-cafe
spec:
  type: LoadBalancer
  ports:
    - name: server
      port: 80
      targetPort: 8080
    - name: management
      port: 9990
      targetPort: 9990
  selector:
    app: azure-cafe
