apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-cafe
  namespace: default
spec:
  selector:
    matchLabels:
      app: azure-cafe
  replicas: 2
  template:
    metadata:
      name: azure-cafe
      labels:
        app: azure-cafe
    spec:
      containers:
      - name: azure-cafe
        image: rezarahman/azure-cafe:v2
        env:
        - name: APPLICATION_INSIGHTS_KEY
          valueFrom:
            configMapKeyRef:
              name: application-insights-key
              key: APPLICATION_INSIGHTS_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: azure-cafe
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: azure-cafe
