apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-cafe
  namespace: default
spec:
  selector:
    matchLabels:
      app: azure-cafe
  replicas: 2
  template:
    metadata:
      name: azure-cafe
      labels:
        app: azure-cafe
    spec:
      containers:
      - name: azure-cafe
        image: rezarahman/azure-cafe:v1
        ports:
        - containerPort: 8080
        - containerPort: 9990
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9990
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9990
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1        
        env:
        - name: APPLICATION_INSIGHTS_KEY
          valueFrom:
            configMapKeyRef:
              name: application-insights-key
              key: APPLICATION_INSIGHTS_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: azure-cafe
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: azure-cafe
